// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Tests
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("RandomGroupAssignment")]
    public partial class RandomGroupAssignmentFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
#line 1 "RandomGroupAssignment.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "", "RandomGroupAssignment", "Help find people with whom someone has not yet worked", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("One set of groups")]
        public virtual void OneSetOfGroups()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("One set of groups", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 5
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "Name"});
                table1.AddRow(new string[] {
                            "Adam"});
                table1.AddRow(new string[] {
                            "Benjamin"});
                table1.AddRow(new string[] {
                            "Caleb"});
                table1.AddRow(new string[] {
                            "Daniel"});
#line 6
 testRunner.Given("the following students", ((string)(null)), table1, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "Member1",
                            "Member2"});
                table2.AddRow(new string[] {
                            "Adam",
                            "Benjamin"});
                table2.AddRow(new string[] {
                            "Caleb",
                            "Daniel"});
#line 12
 testRunner.And("group set 1 was", ((string)(null)), table2, "And ");
#line hidden
#line 16
 testRunner.When("I go to set up group set 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "Possible Partners"});
                table3.AddRow(new string[] {
                            "Caleb"});
                table3.AddRow(new string[] {
                            "Daniel"});
#line 17
 testRunner.Then("Adam can work with", ((string)(null)), table3, "Then ");
#line hidden
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "Possible Partners"});
                table4.AddRow(new string[] {
                            "Adam"});
                table4.AddRow(new string[] {
                            "Benjamin"});
#line 21
 testRunner.And("Caleb can work with", ((string)(null)), table4, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Two sets of groups")]
        public virtual void TwoSetsOfGroups()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Two sets of groups", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 26
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "Name"});
                table5.AddRow(new string[] {
                            "Adam"});
                table5.AddRow(new string[] {
                            "Benjamin"});
                table5.AddRow(new string[] {
                            "Caleb"});
                table5.AddRow(new string[] {
                            "Daniel"});
#line 27
 testRunner.Given("the following students", ((string)(null)), table5, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                            "Member1",
                            "Member2"});
                table6.AddRow(new string[] {
                            "Adam",
                            "Benjamin"});
                table6.AddRow(new string[] {
                            "Caleb",
                            "Daniel"});
#line 33
 testRunner.And("group set 1 was", ((string)(null)), table6, "And ");
#line hidden
                TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                            "Member1",
                            "Member2"});
                table7.AddRow(new string[] {
                            "Adam",
                            "Caleb"});
                table7.AddRow(new string[] {
                            "Benjamin",
                            "Daniel"});
#line 37
 testRunner.And("group set 2 was", ((string)(null)), table7, "And ");
#line hidden
#line 41
 testRunner.When("I go to set up group set 3", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                            "Possible Partners"});
                table8.AddRow(new string[] {
                            "Daniel"});
#line 42
 testRunner.Then("Adam can work with", ((string)(null)), table8, "Then ");
#line hidden
                TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                            "Possible Partners"});
                table9.AddRow(new string[] {
                            "Benjamin"});
#line 45
 testRunner.And("Caleb can work with", ((string)(null)), table9, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("One set of three-member groups")]
        public virtual void OneSetOfThree_MemberGroups()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("One set of three-member groups", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 49
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                            "Name"});
                table10.AddRow(new string[] {
                            "Adam"});
                table10.AddRow(new string[] {
                            "Benjamin"});
                table10.AddRow(new string[] {
                            "Caleb"});
                table10.AddRow(new string[] {
                            "Daniel"});
                table10.AddRow(new string[] {
                            "Ephraim"});
                table10.AddRow(new string[] {
                            "Frank"});
#line 50
 testRunner.Given("the following students", ((string)(null)), table10, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                            "Member1",
                            "Member2",
                            "Member3"});
                table11.AddRow(new string[] {
                            "Adam",
                            "Benjamin",
                            "Caleb"});
                table11.AddRow(new string[] {
                            "Daniel",
                            "Ephraim",
                            "Frank"});
#line 58
 testRunner.And("group set 1 was", ((string)(null)), table11, "And ");
#line hidden
#line 62
 testRunner.When("I go to set up group set 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                            "Possible Partners"});
                table12.AddRow(new string[] {
                            "Daniel"});
                table12.AddRow(new string[] {
                            "Ephraim"});
                table12.AddRow(new string[] {
                            "Frank"});
#line 63
 testRunner.Then("Adam can work with", ((string)(null)), table12, "Then ");
#line hidden
                TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                            "Possible Partners"});
                table13.AddRow(new string[] {
                            "Adam"});
                table13.AddRow(new string[] {
                            "Benjamin"});
                table13.AddRow(new string[] {
                            "Caleb"});
#line 68
 testRunner.And("Daniel can work with", ((string)(null)), table13, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Two sets of three-member groups")]
        public virtual void TwoSetsOfThree_MemberGroups()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Two sets of three-member groups", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 74
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                            "Name"});
                table14.AddRow(new string[] {
                            "Adam"});
                table14.AddRow(new string[] {
                            "Benjamin"});
                table14.AddRow(new string[] {
                            "Caleb"});
                table14.AddRow(new string[] {
                            "Daniel"});
                table14.AddRow(new string[] {
                            "Ephraim"});
                table14.AddRow(new string[] {
                            "Frank"});
#line 75
 testRunner.Given("the following students", ((string)(null)), table14, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                            "Member1",
                            "Member2",
                            "Member3"});
                table15.AddRow(new string[] {
                            "Adam",
                            "Benjamin",
                            "Caleb"});
                table15.AddRow(new string[] {
                            "Daniel",
                            "Ephraim",
                            "Frank"});
#line 83
 testRunner.And("group set 1 was", ((string)(null)), table15, "And ");
#line hidden
                TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                            "Member1",
                            "Member2",
                            "Member3"});
                table16.AddRow(new string[] {
                            "Adam",
                            "Daniel",
                            "Ephraim"});
                table16.AddRow(new string[] {
                            "Benjamin",
                            "Caleb",
                            "Frank"});
#line 87
 testRunner.And("group set 2 was", ((string)(null)), table16, "And ");
#line hidden
#line 91
 testRunner.When("I go to set up group set 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                            "Possible Partners"});
                table17.AddRow(new string[] {
                            "Frank"});
#line 92
 testRunner.Then("Adam can work with", ((string)(null)), table17, "Then ");
#line hidden
                TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                            "Possible Partners"});
                table18.AddRow(new string[] {
                            "Ephraim"});
                table18.AddRow(new string[] {
                            "Frank"});
#line 95
 testRunner.And("Benjamin can work with", ((string)(null)), table18, "And ");
#line hidden
                TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                            "Possible Partners"});
                table19.AddRow(new string[] {
                            "Daniel"});
                table19.AddRow(new string[] {
                            "Ephraim"});
#line 99
 testRunner.And("Caleb can work with", ((string)(null)), table19, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
